"""The publication ledger: what this page said, when, and which model said it.

⛔ **THE RULE THIS MODULE EXISTS TO ENFORCE — attribution, not re-derivability.**

Owner's ruling, 2026-08-30, after ten pinned claims were found sourced to
``run:turnout_tilt_da=1``, a lever ``run_model`` no longer has:

> *"The model will change and how an old model reached something can only be
> recorded. Every forecast value is live at one point and it is bound to be
> superseded — the old value going into the history for that token. We need to
> be able to say what values were, when that was, what model generated it.
> Earlier insistence of always being able to re-run the model is only true of
> values generated by the current model and does not make sense for older values
> generated by older models. We must just be able to say what it was and why."*

Re-derivability is a property of the *current* model's outputs. Demanding it of
the past means either deleting your own history or never retiring a mechanism.
So a published figure must be **attributable** — it must name what it was, when
it was true, and which run produced it — and it need not be recomputable.

**⛔ AND THE SECOND CLAUSE, WHICH IS THE ONE THAT KEEPS THIS HONEST.** Attribution
does not make a stale figure publishable. A figure that has been superseded may
appear **only in a dated context** — "as of 7 August the model said …" — never in
live present tense. Without that clause this module would have licensed
publishing stale numbers with a footnote, which is worse than the refusal the
build has been issuing since 17 August. :func:`dated_context_violations` is the
check, and it is meant to be fatal.

**Bitemporal, and both axes are load-bearing.** This is Slowly Changing Dimension
Type 2, the standard pattern:

* ``as_of``        — VALID time. The run's input cut-off: what the model knew.
* ``published_at`` — TRANSACTION time. When we told the world.

They are not the same and the gap between them is where the eleven-day failure
lived. Without ``as_of`` you cannot answer the one question a hostile reviewer
actually asks — *"what did your model say on 20 September, and on what
evidence?"* — because ``published_at`` alone cannot distinguish a re-publication
from a re-estimation.

**``change_class`` is the field that does the work.** A recompute, a data
revision, a mechanism change and a bug fix produce an identical supersession row
without it, and "the model moved" and "we were wrong" are different sentences
that a reader is entitled to have distinguished. Lineage discipline is precisely
the practice of separating them.

**Append-only.** A row is never rewritten. ``superseded_at`` is a convenience,
not the source of truth: everything callers need is derivable by ordering on
``published_at``, which keeps the file genuinely append-only and means a failed
close-out write cannot corrupt the page.

**Tracked by git, unlike what it describes.** ``data/**`` is gitignored, so the
model outputs have no version history — which is exactly why ``pools`` carries an
artefact key. Same idea one layer out: the ledger goes in git even though the
bytes it attests to do not. ``src/archive.py`` makes the same argument for the
raw inputs.
"""
from __future__ import annotations

import dataclasses
import datetime as dt
import hashlib
import json
import unicodedata
from pathlib import Path
from typing import Any, Iterable

SCHEMA = 1

#: ⛔ RESOLVED IN THE BODY, NEVER AS A DEFAULT ARGUMENT. `root: Path =
#: LEDGER_ROOT` evaluates once at import, so rebinding `publication.LEDGER_ROOT`
#: afterwards would change nothing and a test that pointed the ledger at a
#: tmpdir would silently write to the real one. That is the `LEVEL_DF` defect of
#: MODEL-LOG §1.33 — swept at six values for byte-identical output because the
#: sweep never reached the code. The guard
#: `test_no_numeric_module_constant_is_a_default_argument` caught this module
#: doing it three times on 2026-08-31.
LEDGER_ROOT = Path("publications")

#: A supersession is one of these, and the difference is not cosmetic. It is
#: what lets the page say "the model was re-estimated" rather than "we were
#: wrong", or admit the second when it is true.
CHANGE_CLASSES = ("recompute", "data_revision", "mechanism", "bugfix")

#: How a figure moved, from the reader's side rather than the model's.
#:   new       — first publication of this token
#:   nominal   — a STRING changed; the sentence may now mean something else
#:   material  — moved beyond the token's declared tolerance
#:   minor     — moved, within tolerance
#:   rounding  — the raw value moved but the displayed glyph did not
#:   none      — no movement at all
MOVEMENTS = ("new", "nominal", "material", "minor", "rounding", "none")


def _utc(when: dt.datetime | None = None) -> str:
    when = when or dt.datetime.now(dt.timezone.utc)
    return when.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha(path: Path) -> str | None:
    if not path.is_file():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def normalise_string(value: Any) -> str:
    """NFC, whitespace-collapsed, stripped — and CASE-SENSITIVE, deliberately.

    "the ANC" and "The ANC" read differently on the page, so a difference
    between them is a change a reader should be told about. There is no near
    miss for a string: it either says the same thing or it does not, which is
    why a string token may never carry a numeric tolerance.
    """
    return unicodedata.normalize("NFC", " ".join(str(value).split()))


@dataclasses.dataclass(frozen=True)
class Row:
    """One token, as published once. Never mutated after it is written."""

    token: str
    value: Any                  # the RAW value — see `display` for why both
    display: str                # what the reader actually saw
    fmt: str | None
    source: str
    model_run_id: str
    run_at: str | None          # when the model ran
    as_of: str | None           # VALID time: the run's input cut-off
    published_at: str           # TRANSACTION time
    change_class: str | None
    reason: str | None
    movement: str
    superseded_at: str | None = None

    def as_json(self) -> dict:
        d = dataclasses.asdict(self)
        d["schema"] = SCHEMA
        return d


def display_scale(fmt: str | None) -> float:
    """Multiplier from a token's RAW value to the units the reader sees.

    ⛔ THE INCONSISTENCY THIS RESOLVES IS ALREADY IN THE REGISTRY, and it is the
    kind that produces a wrong answer with no symptom. The same kind of quantity
    is stored two ways:

        claim_da_share_surged   value = 41       (a percentage, as points)
        p_da_largest            resolves to 0.7122  (a percentage, as a fraction)

    So "tolerance = 3" meant three points against the first and three HUNDRED
    points against the second. Every move on a free percentage classified as
    `minor` and no reader would ever have been told a figure changed.

    **The rule, now enforced in one place: `tolerance` is ALWAYS in DISPLAY
    units — the units a reader sees on the page.** Three points is `3`, three
    seats is `3`, fifteen thousand votes is `15000`. Whoever writes a tolerance
    writes the number they would say out loud, and this function converts the
    model's raw value to meet it. Nothing in the registry has to change.
    """
    return 100.0 if fmt and str(fmt).startswith("pct") else 1.0


def _is_nominal(value: Any) -> bool:
    return isinstance(value, str)


def classify(previous: Row | None, value: Any, display: str,
             tolerance: Any = None, fmt: str | None = None) -> str:
    """How a figure moved, from the reader's side.

    ⚠️ ``rounding`` exists because a raw move that does not change the displayed
    glyph is invisible to a reader and must not be marked inline — a mark that
    fires when nothing visible changed trains readers to ignore marks. It is
    still RECORDED, and disclosed in aggregate, because suppressing it silently
    is the original sin this module exists to prevent. That is why every row
    carries BOTH ``value`` and ``display``: the case cannot be detected from the
    rendered string alone.
    """
    if previous is None:
        return "new"
    if _is_nominal(value) or _is_nominal(previous.value):
        return ("nominal"
                if normalise_string(value) != normalise_string(previous.value)
                else "none")
    try:
        moved = abs(float(value) - float(previous.value))
    except (TypeError, ValueError):
        return "nominal" if display != previous.display else "none"
    if display != previous.display:
        if tolerance is not None:
            try:
                tol = float(tolerance)
            except (TypeError, ValueError):
                return "material"
            # TOLERANCE IS IN DISPLAY UNITS. See `display_scale` for why the
            # registry could not previously be read consistently. The raw move
            # is converted to the reader's units and compared there, so a
            # percentage tolerance of 3 means three POINTS whether the token
            # stores 0.71 or 71.
            scale = display_scale(fmt if fmt is not None else previous.fmt)
            moved_shown = moved * scale
            # The remaining trap points the other way: a tolerance written in
            # FRACTION units against a percentage (0.03 meaning "3 points")
            # would make a tenth of a point material. Loud, not silent — but
            # still wrong, and cheap to name.
            if scale != 1.0 and 0 < tol < 0.5:
                raise ValueError(
                    f"{previous.token}: tolerance {tol:g} on a {fmt or previous.fmt!r} "
                    f"token. Tolerance is in DISPLAY units — three percentage "
                    f"points is `3`, not `0.03`. As written, a move of "
                    f"{tol * 100:g} of one point would be reported to readers "
                    f"as a material revision.")
            return "material" if moved_shown > tol else "minor"
        return "material"
    return "rounding" if moved > 1e-12 else "none"


def history(city: str, *, root: Path | None = None) -> list[Row]:
    """Every row ever published for this city, oldest first."""
    root = LEDGER_ROOT if root is None else root
    path = root / city / "ledger.jsonl"
    if not path.is_file():
        return []
    out: list[Row] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        d.pop("schema", None)
        out.append(Row(**d))
    return sorted(out, key=lambda r: r.published_at)


def latest(city: str, *, root: Path | None = None) -> dict[str, Row]:
    """The current published row per token, by publication order."""
    root = LEDGER_ROOT if root is None else root
    out: dict[str, Row] = {}
    for row in history(city, root=root):
        out[row.token] = row
    return out


def append(city: str, rows: Iterable[Row], *, root: Path | None = None) -> int:
    """Append rows. Never rewrites, never reorders, never deduplicates."""
    root = LEDGER_ROOT if root is None else root
    path = root / city / "ledger.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with path.open("a", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row.as_json(), sort_keys=True) + "\n")
            n += 1
    return n


def run_identity(processed: Path) -> dict:
    """Who produced the figures — enough to attribute, not to re-derive.

    ⚠️ A TIMESTAMP SAYS *WHEN*, NOT *WHAT*. `_generated` was added to
    `forecast_summary.json` on 2026-08-30 and is necessary but not sufficient:
    two runs a minute apart on different code are different runs and a date
    cannot tell them apart. Attribution needs the code and the inputs named too,
    which is why the git sha and the pool artefact keys are here.
    """
    summary_path = processed / "forecast_summary.json"
    summary: dict = {}
    if summary_path.is_file():
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            summary = {}
    run_at = summary.get("_generated")
    draws = summary.get("_draws")
    ident = {
        "run_at": run_at,
        "draws": draws,
        "forecast_summary_sha256": _sha(summary_path),
        "seat_draws_sha256": _sha(processed / "seat_draws.csv"),
    }
    # `as_of` — VALID time. The best available statement of what the run KNEW.
    # It is the run time until something better exists: a genuine input cut-off
    # would come from the newest input the run consumed, and that is worth
    # building rather than guessing. Recorded as run time and LABELLED, so it is
    # never mistaken for a measured cut-off.
    ident["as_of"] = run_at
    ident["as_of_is"] = "run time; no input cut-off is recorded yet"
    stamp = (run_at or "unknown").replace(":", "").replace("-", "")
    digest = (ident["forecast_summary_sha256"] or "0" * 8)[:8]
    ident["model_run_id"] = f"r-{stamp}-{digest}"
    return ident


def dated_context_violations(rendered: Iterable[dict],
                             ledger: dict[str, Row]) -> list[dict]:
    """⛔ Superseded figures appearing in LIVE PRESENT TENSE. Meant to be fatal.

    This is the second clause of the attribution rule, and without it the rule
    is a licence rather than a discipline. A figure whose mechanism is gone may
    be published — *"as of 7 August the model said the DA would be short by 39
    seats"* — and may not be published as though it were current.

    ``rendered`` is a sequence of ``{"token", "dated"}`` mappings; ``dated`` says
    whether the surrounding prose places the figure in time. The renderer knows
    that and this module cannot infer it, so it is declared rather than guessed.
    """
    out = []
    for span in rendered:
        row = ledger.get(span.get("token", ""))
        if row is None or not row.superseded_at:
            continue
        if not span.get("dated"):
            out.append({
                "token": row.token,
                "display": row.display,
                "superseded_at": row.superseded_at,
                "why": ("published in live present tense, but this figure was "
                        "superseded on " + row.superseded_at + ". A superseded "
                        "figure may appear only in a dated context — 'as of "
                        "<date> the model said …'. Attribution records what it "
                        "was; it does not make it current."),
            })
    return out


def summarise(rows: Iterable[Row]) -> dict:
    """The counts a 'what changed' section needs, in the reader's categories."""
    rows = list(rows)
    by = {m: [r.token for r in rows if r.movement == m] for m in MOVEMENTS}
    return {
        "n": len(rows),
        "by_movement": {k: v for k, v in by.items() if v},
        "n_visible": sum(len(by[m]) for m in ("nominal", "material", "minor")),
        "n_rounding": len(by["rounding"]),
        "nominal": by["nominal"],
    }
